version: "3.8"
services:
    db:
        image: postgres:13
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        env_file:
            - ./.env
        environment:
            - "POSTGRES_DB:${POSTGRES_DB}"
            - "POSTGRES_PASSWORD:${POSTGRES_PASSWORD}"
            - "POSTGRES_USER:${POSTGRES_USER}"


    web:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        restart: always
        env_file: ./.env
        entrypoint: ./scripts/asgi.sh
        volumes:
            - media-data:/var/lib/media/
            - static-data:/var/lib/static
        depends_on:
            - db
        tty: true
    
    nginx:
        build: ./docker/nginx
        restart: always
        volumes:
            - static-data:/var/lib/static/
        ports:
            - 80:80
        depends_on:
            - web

volumes:
  postgres-data:
  media-data:
  static-data:
