version: "3.8"
services:
  web:
    build:
        context: .
        dockerfile: ./docker/django/Dockerfile
    env_file: ./.env.dev
    ports:
      - "8000:8000"
    command: yarn web:dev
    volumes:
      - ./:/home/lang/djangotemplate
      - media:/var/lib/mysite/media/
      - static:/var/lib/mysite/static/
    tty: true

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
  media:
  static:
