# Generated by Django 4.1.5 on 2024-11-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_directmessage_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="content",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="textchannelmessage",
            name="content",
            field=models.CharField(max_length=255),
        ),
    ]
