# Generated by Django 4.1.5 on 2024-11-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_directmessage_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directmessagechannel",
            name="name",
        ),
        migrations.AddField(
            model_name="role",
            name="default_role",
            field=models.BooleanField(default=False),
        ),
    ]
