# Generated by Django 4.1.5 on 2024-11-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_directmessagechannel_name_role_default_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="invite_link",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
